sonar.projectKey=flask-devops-app
sonar.projectName=Flask DevOps App
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.sourceEncoding=UTF-8